#!/usr/bin/env python3

import argparse
import os
import sys
from os import path
from subprocess import check_call

import distro

parser = argparse.ArgumentParser(description="Run Pop!_OS build process")
parser.add_argument("--dev", action="store_true")
parser.add_argument("--dist", default=distro.codename())
parser.add_argument("--arch", default="amd64")
parser.add_argument("--update", action="store_true")
parser.add_argument("repo")
args = parser.parse_args(sys.argv[1:])


def ppa_url(ppa):
    return "http://ppa.launchpad.net/" + ppa + "/ubuntu"


apt_key = ".iso.asc"
if args.dev:
    apt_release = "http://apt.pop-os.org/release-ubuntu"
    apt_proposed = "http://apt.pop-os.org/staging-ubuntu/master"
else:
    apt_release = "http://apt.pop-os.org/release"
    apt_proposed = "http://apt.pop-os.org/staging/master"


chroot_path = "/srv/chroot/" + args.dist + "-" + args.arch + "-sbuild"
if not path.exists(chroot_path):
    check_call(
        [
            "sudo",
            "sbuild-createchroot",
            "--include=gnupg",
            "--components=main,restricted,universe,multiverse",
            "--arch=" + args.arch,
            args.dist,
            chroot_path,
            "http://apt.pop-os.org/ubuntu",
        ]
    )

if args.update:
    check_call(
        [
            "sudo",
            "sbuild-update",
            "--update",
            "--dist-upgrade",
            "--clean",
            "--autoclean",
            "--autoremove",
            "--arch=" + args.arch,
            args.dist,
        ]
    )

sbuild = [
    "sbuild",
    "--arch=" + args.arch,
    "--dist=" + args.dist,
    "--extra-repository=deb http://apt.pop-os.org/ubuntu "
    + args.dist
    + "-updates main restricted universe multiverse",
    "--extra-repository=deb-src http://apt.pop-os.org/ubuntu "
    + args.dist
    + "-updates main restricted universe multiverse",
    "--extra-repository=deb http://apt.pop-os.org/ubuntu "
    + args.dist
    + "-security main restricted universe multiverse",
    "--extra-repository=deb-src http://apt.pop-os.org/ubuntu "
    + args.dist
    + "-security main restricted universe multiverse",
    "--extra-repository=deb " + apt_release + " " + args.dist + " main",
    "--extra-repository=deb-src " + apt_release + " " + args.dist + " main",
    "--extra-repository=deb " + apt_proposed + " " + args.dist + " main",
    "--extra-repository=deb-src " + apt_proposed + " " + args.dist + " main",
    "--extra-repository-key=" + path.join(os.getcwd(), "scripts", apt_key),
    "--no-apt-distupgrade",
    "--no-run-lintian",
]

check_call(sbuild, cwd=args.repo)
